### ISSUE TITLE
Question about "celltrek_vis" results

### ISSUE THREAD

**Issue by ZeroLi-Bio** [navinlabcode/CellTrek#4]
Hi,

Thank you for providing this great tool for ST research! 
While when I tried to run CellTrek on own samples (NOT 10X platform), I met a problem. Which is in the step of Celltrek _vis, the plot is not same shape as original ST seurat object. It is a Oval shape (as pitcture 1).  
The original ST spatial plot is also attached below as pitcture 2.

The original ST seurat object does not store a coresponding real image,  its @images is like below( pitcture 3). 
Could you give a hint on how to fix this?

Thanks in advance!

Best,
pitcture 1:
![newplot](https://user-images.githubusercontent.com/48876554/160342345-144175d0-cf2d-4a4c-bff4-2105078d0acd.png)
pitcture 2: 
![original_ST_plot](https://user-images.githubusercontent.com/48876554/160342564-3a190458-0c75-404c-9507-34c851541516.png)
pitcture 3: 
![Snipaste_2022-03-28_14-48-41](https://user-images.githubusercontent.com/48876554/160342359-b36a2a1a-84f9-4939-b855-65105e85fda4.png)

**Comment by WandeRum** [comment]
Hi. This is very interesting. Since all of our default settings were based on the 10X Visium data, I guess there might be something incompatible here. First, can you check the DimPlot(obj, reduction='celltrek_raw') to see if the overall mapping looks good? If so, it could be the repelling problem, then you could simply change the repel_r and repel_iter to a smaller number. If not, I guess there are still some structural differences between the data you have vs the Visium one which requires a thorough check of the data structure.

**Comment by ZeroLi-Bio** [comment]
> Yes, the DimPlot(obj, reduction='celltrek_raw') looks good. I will give it a try on smaller repel_r and repel_iter.
Thank you!
![dimplot](https://user-images.githubusercontent.com/48876554/163901313-f59b405b-3156-4429-94bd-bb2c9e41c2e8.png)
